[build]
  command = "npm run build"
  publish = "dist"

# Redirecciones para React Router (SPA)
# Esto asegura que Netlify no intente buscar rutas en el servidor,
# sino que devuelva el index.html y deje que el navegador maneje la ruta.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Desactivamos explícitamente cualquier carpeta de funciones
[functions]
  directory = "non_existent_folder"
